### ISSUE TITLE
Publish DotNet.ProjInfo.Workspace.FCS as nuget

### ISSUE THREAD

**Issue by nojaf** [enricosada/dotnet-proj-info#35]
Hello @enricosada, I've would like to use the functionality in #32 to get Fable to compile `fsx` files.
What is the plan on releasing on `DotNet.ProjInfo.Workspace.FCS` as nuget package?

**Comment by enricosada** [comment]
Yes, both `Dotnet.ProjInfo.Workspace` and `Dotnet.ProjInfo.Workspace.FCS`

In the next days

**Comment by enricosada** [comment]
Done.

- https://www.nuget.org/packages/Dotnet.ProjInfo.Workspace.FCS/0.31.0
- https://www.nuget.org/packages/Dotnet.ProjInfo.Workspace/0.31.0

@nojaf i'll upgrade FSAC soon too, if you want to wait when is more stable.

Please ping me if you find issues.
