### ISSUE TITLE
Request for 20 Binary

### ISSUE THREAD

**Issue by matthid** [enricosada/dotnet-proj-info#7]
Similar request to https://github.com/enricosada/dotnet-mergenupkg/issues/3

See https://github.com/matthid/dotnet-proj-info/commit/b612c40d3ee9e84c5d9b08228d495449e9159cef

**Comment by enricosada** [comment]
@matthid you use that for? just curious.
The library works better for tools, and maybe i need to move the the project tree navigation here from FSAC for next version.

**Comment by matthid** [comment]
I thought about integrating it into paket. Finally I decided against it. For historical reasons we already have a project file parser/evaluator in paket so I used that instead.
